### ISSUE TITLE
Compilation issue in redis_module macro when updating from 0.18.0(to any version further)

### ISSUE THREAD

**Issue by let4be** [RedisLabsModules/redismodule-rs#188]
```
error[E0308]: mismatched types
   --> redis-calc/src/lib.rs:138:1
    |
138 | / redis_module! {
139 | |     name: "crusty.calc",
140 | |     version: 1,
141 | |     data_types: [],
...   |
145 | |     ],
146 | | }
    | |_^ expected struct `std::string::String`, found struct `RedisString`
    |
    = note: expected struct `Vec<std::string::String>`
               found struct `Vec<RedisString>`
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

module definition:
```rust
redis_module! {
    name: "crusty.calc",
    version: 1,
    data_types: [],
    commands: [
        ["crusty.calc.topk.add", topk_add, "", 0, 0, 0],
        ["crusty.calc.topk.consume", topk_consume, "", 0, 0, 0],
    ],
}
```

I don't see any code in examples to be updated to reflect needed changes

**Comment by gkorland** [comment]
@let4be are you still getting this error? which OS are you using? Which command do you use to compile the code?

**Comment by let4be** [comment]
`uname -a`
`Linux dev-virtual-machine 5.8.0-63-generic #71-Ubuntu SMP Tue Jul 13 15:59:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

I use `cargo build` as always

`cargo.toml`:
`redis-module = "~0.20.0"`

Ideas?

**Comment by let4be** [comment]
Updating version in `cargo.toml` to the latest(`redis-module = "~0.23.0"`) doesn't seem to solve the problem

**Comment by let4be** [comment]
I also just tried clearing package cache with (`cargo-cache -a`) just in case, but as I expected it didn't resolve this issue
There's clearly some kind of type mismatch in this magical macro that declares redis module

**Comment by let4be** [comment]
full dump of `cargo build --verbose`
```
dev@dev-virtual-machine:~/rust/github.com/let4be/crusty/redis-calc$ cargo build --verbose
       Fresh unicode-xid v0.2.2
       Fresh version_check v0.9.3
       Fresh cfg-if v1.0.0
       Fresh glob v0.3.0
       Fresh regex-syntax v0.6.25
       Fresh tap v1.0.1
       Fresh wyz v0.2.0
       Fresh funty v1.1.0
       Fresh autocfg v1.0.1
       Fresh unicode-width v0.1.8
       Fresh lazy_static v1.4.0
       Fresh bitflags v1.3.2
       Fresh termcolor v1.1.2
       Fresh strsim v0.8.0
       Fresh vec_map v0.8.2
       Fresh ansi_term v0.11.0
       Fresh humantime v2.1.0
       Fresh rustc-hash v1.1.0
       Fresh unicode-xid v0.0.4
       Fresh tinyvec_macros v0.1.0
       Fresh lazycell v1.3.0
       Fresh shlex v1.1.0
       Fresh peeking_take_while v0.1.2
       Fresh cc v1.0.70
       Fresh quote v0.3.15
       Fresh unicode-segmentation v1.8.0
       Fresh matches v0.1.9
       Fresh unicode-bidi v0.3.6
       Fresh percent-encoding v2.1.0
       Fresh if_chain v1.0.2
       Fresh itoa v0.4.8
       Fresh either v1.6.1
       Fresh textwrap v0.11.0
       Fresh libloading v0.7.0
       Fresh synom v0.11.3
       Fresh tinyvec v1.4.0
       Fresh heck v0.3.3
       Fresh proc-macro2 v1.0.29
       Fresh memchr v2.4.1
       Fresh libc v0.2.102
       Fresh radium v0.5.3
       Fresh log v0.4.14
       Fresh form_urlencoded v1.0.1
       Fresh itertools v0.10.1
       Fresh quote v1.0.9
       Fresh aho-corasick v0.7.18
       Fresh bitvec v0.19.5
       Fresh atty v0.2.14
       Fresh clang-sys v1.2.2
       Fresh which v3.1.1
       Fresh num-traits v0.2.14
       Fresh unicode-normalization v0.1.19
       Fresh syn v0.11.11
       Fresh ryu v1.0.5
       Fresh syn v1.0.76
       Fresh regex v1.5.4
       Fresh nom v6.1.2
       Fresh clap v2.33.3
       Fresh num-traits v0.1.43
       Fresh proc-macro-error-attr v1.0.4
       Fresh idna v0.2.3
       Fresh anyhow v1.0.44
       Fresh env_logger v0.8.4
       Fresh cexpr v0.5.0
       Fresh serde_derive v1.0.130
       Fresh strum_macros v0.21.1
       Fresh proc-macro-error v1.0.4
       Fresh enum-primitive-derive v0.1.2
       Fresh validator_types v0.14.0
       Fresh url v2.2.2
       Fresh thiserror-impl v1.0.29
       Fresh bindgen v0.59.1
       Fresh serde v1.0.130
       Fresh validator_derive v0.14.0
       Fresh thiserror v1.0.29
       Fresh serde_json v1.0.68
       Fresh interop v0.1.0 (/home/dev/rust/github.com/let4be/crusty/interop)
       Fresh validator v0.14.0
       Fresh redis-module v0.23.0
       Fresh redis-utils v0.1.0 (/home/dev/rust/github.com/let4be/crusty/redis-utils)
   Compiling redis-calc v0.1.0 (/home/dev/rust/github.com/let4be/crusty/redis-calc)
     Running `rustc --crate-name redis_calc --edition=2018 redis-calc/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type cdylib --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C debug-assertions=off -C overflow-checks=on -C metadata=ec60168e409da95f --out-dir /home/dev/rust/github.com/let4be/crusty/target/debug/deps -C incremental=/home/dev/rust/github.com/let4be/crusty/target/debug/incremental -L dependency=/home/dev/rust/github.com/let4be/crusty/target/debug/deps --extern anyhow=/home/dev/rust/github.com/let4be/crusty/target/debug/deps/libanyhow-5ca33acbd7c8957c.rlib --extern interop=/home/dev/rust/github.com/let4be/crusty/target/debug/deps/libinterop-05fc22913061e276.rlib --extern itertools=/home/dev/rust/github.com/let4be/crusty/target/debug/deps/libitertools-8ed3211fd56c203f.rlib --extern redis_module=/home/dev/rust/github.com/let4be/crusty/target/debug/deps/libredis_module-d0595059d3d03be6.rlib --extern redis_utils=/home/dev/rust/github.com/let4be/crusty/target/debug/deps/libredis_utils-3a9b81a0ba164f31.rlib --extern serde=/home/dev/rust/github.com/let4be/crusty/target/debug/deps/libserde-4ae1da4d30810e54.rlib --extern serde_json=/home/dev/rust/github.com/let4be/crusty/target/debug/deps/libserde_json-dcb2ed7429210918.rlib --extern thiserror=/home/dev/rust/github.com/let4be/crusty/target/debug/deps/libthiserror-28c866bbb9b53e16.rlib --extern validator=/home/dev/rust/github.com/let4be/crusty/target/debug/deps/libvalidator-bb1e9931188a09a9.rlib -L native=/home/dev/rust/github.com/let4be/crusty/target/debug/build/redis-module-19b504d5a0b46412/out`
error[E0308]: mismatched types
   --> redis-calc/src/lib.rs:138:1
    |
138 | / redis_module! {
139 | |     name: "crusty.calc",
140 | |     version: 1,
141 | |     data_types: [],
...   |
145 | |     ],
146 | | }
    | |_^ expected struct `std::string::String`, found struct `RedisString`
    |
    = note: expected struct `Vec<std::string::String>`
               found struct `Vec<RedisString>`
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
   --> redis-calc/src/lib.rs:138:1
    |
138 | / redis_module! {
139 | |     name: "crusty.calc",
140 | |     version: 1,
141 | |     data_types: [],
...   |
145 | |     ],
146 | | }
    | |_^ expected struct `std::string::String`, found struct `RedisString`
    |
    = note: expected struct `Vec<std::string::String>`
               found struct `Vec<RedisString>`
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `redis-calc`

Caused by:
  process didn't exit successfully: `rustc --crate-name redis_calc --edition=2018 redis-calc/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type cdylib --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C debug-assertions=off -C overflow-checks=on -C metadata=ec60168e409da95f --out-dir /home/dev/rust/github.com/let4be/crusty/target/debug/deps -C incremental=/home/dev/rust/github.com/let4be/crusty/target/debug/incremental -L dependency=/home/dev/rust/github.com/let4be/crusty/target/debug/deps --extern anyhow=/home/dev/rust/github.com/let4be/crusty/target/debug/deps/libanyhow-5ca33acbd7c8957c.rlib --extern interop=/home/dev/rust/github.com/let4be/crusty/target/debug/deps/libinterop-05fc22913061e276.rlib --extern itertools=/home/dev/rust/github.com/let4be/crusty/target/debug/deps/libitertools-8ed3211fd56c203f.rlib --extern redis_module=/home/dev/rust/github.com/let4be/crusty/target/debug/deps/libredis_module-d0595059d3d03be6.rlib --extern redis_utils=/home/dev/rust/github.com/let4be/crusty/target/debug/deps/libredis_utils-3a9b81a0ba164f31.rlib --extern serde=/home/dev/rust/github.com/let4be/crusty/target/debug/deps/libserde-4ae1da4d30810e54.rlib --extern serde_json=/home/dev/rust/github.com/let4be/crusty/target/debug/deps/libserde_json-dcb2ed7429210918.rlib --extern thiserror=/home/dev/rust/github.com/let4be/crusty/target/debug/deps/libthiserror-28c866bbb9b53e16.rlib --extern validator=/home/dev/rust/github.com/let4be/crusty/target/debug/deps/libvalidator-bb1e9931188a09a9.rlib -L native=/home/dev/rust/github.com/let4be/crusty/target/debug/build/redis-module-19b504d5a0b46412/out` (exit status: 1)
```

**Comment by let4be** [comment]
I'm looking through commit history
Possible culprit: https://github.com/RedisLabsModules/redismodule-rs/commit/abc30ffa964b4d97cb24440307aedea566c1a278

**Comment by let4be** [comment]
My mistake... Looking through this commit I figured out that command arguments were changed
from `fn cmd(ctx: &Context, args: Vec<String>) -> RedisResult`
to `from `fn cmd(ctx: &Context, args: Vec<RedisString>) -> RedisResult`

This caused wrong code being generated by macro and rust really not helping with crypting error messages...
